### ISSUE TITLE
Schema toml format doesn't describe how to specify indexes

### ISSUE THREAD

**Issue by deontologician** [rethinkdb/horizon-docs#71]
If you create a horizon app using `--auto-create-collection` and `--auto-create-indexes`, and then do `hz get-schema` on it, you will get stuff that looks like:

```toml
[collections.test_data]
indexes = ["a","a_b","a_c","a_id","abracadabra","b","field","id_$hz\\_v$","score","time","value_time"]
```

These index names have a particular format that tells horizon how to create the index when it's passed back to `set-schema`, but this isn't documented anywhere. We should document it so people are able to specify their indexes without needing to have horizon autogenerate them first.

@Tryneus can probably give us exact details on how the mapping works
